### ISSUE TITLE
python3 et 2.7 dans le terminal

### ISSUE THREAD

**Issue by Ethan081** [EcoleNumeriqueVivant/photosite#1]
Bonjour, je suis sur Mac. dans le terminal si je tape :~ python j'ouvre le shell en 2.7. Si je tape :~python3 j ai le shell 3.6 . Si je supprime la version 2.7 de l'ordi et que je tape la commande :~python  tomberai- je obligatoirement sur le shell  en 3.6 ?.
Bonne Journee.

**Comment by lbernail** [comment]
Si cest la version installee par defaut sur ton mac je te conseille de ne pas la supprimer
Tu peux mettre un alias (alias python=python3). Si tu choisis ca pense aussi a le faire pour pip.

(si tu veux que ce soit persistant, ajoute le a ton .bashrc ou equivalent en fonction de ton shell)

**Comment by Ethan081** [comment]
Cool, merci , j ai mis les alias dans le fichier .zshrc .Ca tourne niquel.
