### ISSUE TITLE
L'environnement virtuel

### ISSUE THREAD

**Issue by Ethan081** [EcoleNumeriqueVivant/photosite#2]
Bonjour, 
En regardant differents  tutos . Certain conseil de créer un environnement virtuel de programmation (virtualenv) et d'autre non . Le tuto de djangoproject.com ne le spécialisé pas . Est-ce une bonne habitude dans crée un pour chaque projet, ou l'install directement de Django dans le dossier du projet est chose courante.
Merci.

**Comment by ajacoutot** [comment]
Compliqué de répondre à ta question. En fait ça dépend...
Disons que pour un environnement de développement le virtualenv c'est pas mal parce que ça évite de polluer ta machine, notamment en terme de conflit entre les différentes versions des packages de la distribution et celles installés avec pip par exemple.
En gros ça te donne un environnement python isolé et indépendant du reste du système.

**Comment by Ethan081** [comment]
Ok merci de ta reponce
